### ISSUE TITLE
Better error handling for bogus zvariant signatures

### ISSUE THREAD

**Issue by Exidex** [dbus2/zbus#510]
Currently if someone tries to specify signature on zvariant macro that have no chance of working zbus will quietly fail without any meaningful message, only `failed to read from socket` and `BrokenPipe`.

In the example I tried to define enum with VARIANT type for which, _as I found out later_, exists `zvariant::Value` and that my use case isn't supported yet https://github.com/dbus2/zbus/issues/234 

After becoming more familiar with zbus, using `#[zvariant(signature = "...")]` feels like an escape hatch that breaks horribly if not used property. It would be nice to have better error messages and, maybe, somehow restrict or better document usage of zvariant macro

<details>
<summary>Not-so-minimal reproduction example</summary>

src/main.rs:
```rust
use tracing_subscriber::util::SubscriberInitExt;

fn main() {
    tracing_subscriber::fmt::Subscriber::builder()
        .with_max_level(tracing::metadata::LevelFilter::TRACE)
        .finish()
        .init();

    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .unwrap();

    let handle = runtime.handle().clone();
    std::thread::spawn(move || {
        std::thread::sleep(std::time::Duration::from_secs(1));

        handle.block_on(async {
            let conn = zbus::Connection::session().await.unwrap();

            let proxy = ServerProxyProxy::new(&conn).await.unwrap();

            proxy.ping(Property::String("string".to_string())).await.unwrap();
        })
    });

    runtime.block_on(async {
        let _connection = zbus::ConnectionBuilder::session()
            .unwrap()
            .name("org.ThisWillForSureNotCollideWithAnything")
            .unwrap()
            .serve_at("/org/ThisWillForSureNotCollideWithAnything", Server)
            .unwrap()
            .build()
            .await
            .unwrap();

        std::future::pending::<()>().await;
    })
}

#[derive(Debug, serde::Serialize, serde::Deserialize, zbus::zvariant::Type)]
#[zvariant(signature = "(uv)")] // obviously wrong
pub enum Property {
    String(String),
    Number(f64),
    Bool(bool),
}

pub struct Server;

#[zbus::dbus_interface(name = "org.ThisWillForSureNotCollideWithAnything")]
impl Server {
    fn ping(&self, prop: Property) {
        println!("{:?}", prop)
    }
}

#[zbus::dbus_proxy(
default_service = "org.ThisWillForSureNotCollideWithAnything",
default_path = "/org/ThisWillForSureNotCollideWithAnything",
interface = "org.ThisWillForSureNotCollideWithAnything",
)]
trait ServerProxy {
    async fn ping(&self, prop: Property) -> zbus::Result<()>;
}
```
Cargo.toml:
```toml
[package]
name = "zbus-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
tokio = { version = "1.28.1", features = ["rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
```
</details>
