### ISSUE TITLE
Pinning `zvariant_utils` makes it impossible to resolve version conflicts 

### ISSUE THREAD

**Issue by PolyMeilex** [dbus2/zbus#652]
https://github.com/dbus2/zbus/blob/a2e3d17358942b893d74bf593ffb95f5484b3b97/zbus_macros/Cargo.toml#L28
https://github.com/dbus2/zbus/blob/d9b367a4c44fb57bdf820eab6cc743e8e6f89570/zbus_macros/Cargo.toml#L28

zbus 4 pins 1.1, zbus 3 pins 1.0, and both of those versions are part of the same semver 1.x.x so cargo is not able to resolve the version conflict.

(most likely) causes: https://github.com/PolyMeilex/rfd/issues/180

repro:
```toml
[package]
name = "crate_that_uses_4_and_3"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus_macros = "4"
zbus_macros3 = { package = "zbus_macros", version = "3.15"}
````

**Comment by zeenix** [comment]
Not sure what we can do about that. Best option is to port the whole stack to zbus 4 or don't pin zvariant_utils.

I'm happy to reopen it if you have any suggestions on how we can help.

**Comment by zeenix** [comment]
Oh it's zbus pinning it. Sorry I missed that. Still, I don't know what I can do about this. The pinning is done for good reasons.

**Comment by PolyMeilex** [comment]
Sure I get that there are probably reasons for that, but this breaks for people as I updated my lib to zbus 4, but the accessibility stack is and will remain on zbus 3 for some time because of MSRV reasons: https://github.com/odilia-app/atspi/pull/155#issuecomment-1949132789

So I'm stuck with my lib being unusable because I updated zbus to early :smile: 

Even if we can't address that, it would be cool to somehow prevent that in the future (aka. once zbus 5 is a thing)
Could you explain reasons for the pining rather than just letting it bump to 1.1? So I can better understand what is the problem at hand.

**Comment by zeenix** [comment]
> accessibility stack is and will remain on zbus 3 for some time because of MSRV reasons: [odilia-app/atspi#155 (comment)](https://github.com/odilia-app/atspi/pull/155#issuecomment-1949132789)

They sound a lot less sure about that in their next comment so hopefully they'll be able to bump it in the near future.

> So I'm stuck with my lib being unusable because I updated zbus to early 😄 (for people that want to have accessibility in their apps, that is)

You're ahead of your time. Nothing wrong with that. :)

> Could you explain reasons for the pining rather than just letting it bump to 1.1?

TBH I don't remember if zvariant_utils itself has a good reason to be pinned. I do know that we pin the macro crates to ensure compatibility w/o introducing a cyclic dep between the main and the macro crate. It's entirely possible that we just followed the trend. Two things to consider here:

1. Don't we have the same issue with zbus_macros and zbus? If so, we've a good reason there and unpinning zvariant_utils will not get us far.
2. There is a good chance we'll add macros in zvariant_utils. If we don't have a good reason to pin now, we will likely do then. Since we're thinking of future major releases, this will then again be an issue but unpinning would then not be a solution.

**Comment by PolyMeilex** [comment]
> Don't we have the same issue with zbus_macros and zbus? If so, we've a good reason there and unpinning zvariant_utils will not get us far.

Macros crate had a braking version bump, so cargo should not treat it as a single dep, and everything should work as expected.

Utils on the other hand had only a minor bump, therefore cargo treats it as a same dep.

Aka.
This is totally fine to do:
```toml
[dependencies]
zbus_macros = "=4"
zbus_macros2 = { package = "zbus_macros", version = "=3"}
```
This is not:
```toml
[dependencies]
zvariant_utils = "=1.0.1"
zvariant_utils2 = { package = "zvariant_utils", version = "=1.1.0"}
```
